### ISSUE TITLE
Collect data for university 

### ISSUE THREAD

**Issue by linhpha** [UIOWA5830SP19/SPP300#31]
**Describe the issue here**
Extract data from US News for ranking and information about department for different computer science master program in the US

**Comment by Avanti0532** [comment]
Here is the data extracted for universities. I will update it for few more universities.
https://docs.google.com/spreadsheets/d/1tTHUMX_Up723CIVMFeHkblfZ2R5NQVd4E7AbIqAENkc/edit?usp=sharing
