### ISSUE TITLE
Create student profiles

### ISSUE THREAD

**Issue by hpitawela** [UIOWA5830SP19/SPP300#77]
This Epic is an umbrella task for creating student profile feature for Gremester app. The expectation of this features include:
  - Students are able to store their personal information such as: profile picture, undergraduate college, gpa, toefl, gre score, resume, sop, major, research objective
  - Students will be able to view any information the store with the system through the UI
  - Students are able to edit any of the information including updating resume, photo ID, sop, education, grades and that information is reflected in the database
  - Students can keep a list of potential universities where they can update the status of their application if they decide to apply to any of the school. These information will be stored in the database

**Comment by jwryan9** [comment]
What are the requirements for this feature? Lacking description.
